FROM python:3.10-bullseye

RUN mkdir - p /home/django-app

WORKDIR /home/django-app

COPY ./requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["gunicorn", "-b", "0.0.0.0:8000", "temperature_statistics_project.wsgi:application"]

EXPOSE 8000