version: '3.7'

services:
  django-app:
    build: './src/temperature_statistics_project'
    restart: always
    volumes:
      - ./src/temperature_statistics_project/:/home/django-app

    ports:
      - 8000:8000


  nginx:
    build: './nginx'
    restart: always
    ports:
      - 80:80

    volumes:
      - ./src/:/home/app/djangoApp
    depends_on:
      - django-app